### ISSUE TITLE
Saldo negativo em conta corrente

### ISSUE THREAD

**Issue by djairdj** [mauricioHidani/aluraChallengeBankAccount#6]
Durante as movimentações financeiras de conta corrente, o cliente pode ficar com saldo negativo.
Mesmo com saldo negativo o cliente ainda consegue efetivar transferências e assim deixar o saldo ainda mais negativo.
Essa situação faz parte da regra de negócio pensada originamente?
Caso queira fazer uma revisão, o ponto do código que lida com essa questão é no arquivo `OperationCurrentAccService`, dentro do método `transfer`.

**Comment by mauricioHidani** [comment]
Então a ideia é exatamente essa, somente no tipo de conta Corrente, onde aplico uma tarifa bancária pelo valor que seria em tese emprestado (tarifa bancária + taxa de emprestimo).

**Comment by djairdj** [comment]
Ok, explicado.

**Comment by mauricioHidani** [comment]
Mas cara foram muito boas as suas observações, eu que me equivoquei colocando uma coisa na documentação e fazendo outra em código, fui escrevendo o código e não testei bem como deveria 🫡
